badger_view/Controllers/PhotoshootsController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using badger_view.Helpers;
using GenericModals.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CommonHelper;
using Microsoft.AspNetCore.Authorization;
using GenericModals;

namespace badger_view.Controllers
{
    public class PhotoshootsController : Controller
    {
        private ILoginHelper _ILoginHelper;
        private readonly IConfiguration _config;
        private BadgerApiHelper _BadgerApiHelper;
        private CommonHelper.CommonHelper _common = new CommonHelper.CommonHelper();
        public PhotoshootsController(IConfiguration config, ILoginHelper LoginHelper, BadgerApiHelper badgerApiHelper)
        {
            _ILoginHelper = LoginHelper; 
            _config = config;
            _BadgerApiHelper = badgerApiHelper;
        }

        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: List all Photoshoot Products which are not started from this api url "/Photoshoots/listpageview/10"
        URL: /Photoshoots
        Input: Null
        output: dynamic ExpandoObject of ProductPhotoshoot
        */
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var photoshootPagerList = await _BadgerApiHelper.GetAsync<List<ProductPhotoshootRep>>("/Photoshoots/listpageview/0");
            return View("Index", photoshootPagerList);
        }


        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: List all Photoshoots which are in-progress from this api url "/Photoshoots/inprogress/"
        URL: /Photoshoots/shootInProgress
        Input: Null
        output: dynamic ExpandoObject of ProductPhotoshoot
        */
        [Authorize]
        [HttpGet("photoshoots/shootInProgress/{selectPhotoshootId}")]
        public async Task<IActionResult> shootInProgress(string selectPhotoshootId)
        {
            var singleShoot = await _BadgerApiHelper.GetAsync<ProductPhotoshootInProgressRep>("/Photoshoots/inprogress/" + selectPhotoshootId);
            ProductPhotoshootInProgressPagerList photoshootInProgress = new ProductPhotoshootInProgressPagerList
            {
                photoshootsInprogress = new List<ProductPhotoshootInProgressRep> { singleShoot }
            };
            
            dynamic photoshootInProgressModal = new ExpandoObject();
            photoshootInProgressModal.Lists = photoshootInProgress.photoshootsInprogress;
            photoshootInProgressModal.SelectedPhotoshoot = selectPhotoshootId;

            return View("ShootInProgress", photoshootInProgressModal);
        }

        [Authorize]
        [HttpGet("photoshoots/shootInProgress/")]
        public async Task<IActionResult> shootInProgress()
        {
            ProductPhotoshootInProgressPagerList photoshootInProgress = await _BadgerApiHelper.GenericGetAsync<ProductPhotoshootInProgressPagerList>("/Photoshoots/inprogress/");
            string selectPhotoshootId = "0";
            dynamic photoshootInProgressModal = new ExpandoObject();
            photoshootInProgressModal.Lists = photoshootInProgress.photoshootsInprogress;
            photoshootInProgressModal.SelectedPhotoshoot = selectPhotoshootId;

            return View("ShootInProgress", photoshootInProgressModal);
        }


        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: get all photoshoot products by photoshoot id which are in-progress from this api url "/Photoshoots/GetPhotoshootsProducts/"
        URL: /Photoshoots/getPhotoshootInProgressProducts/1
        Input: Photoshoot Id
        output: dynamic ExpandoObject of PhotoshootInProgressProducts
        */
        [Authorize]
        [HttpGet("photoshoots/getPhotoshootInProgressProducts/{photoshootId}")]
        public async Task<IActionResult> getPhotoshootInProgressProducts(int photoshootId)
        {
            string callUrl = "/Photoshoots/GetPhotoshootsProducts/" + photoshootId;
            ProductPhotoshootPagerList photoshootPagerList = await _BadgerApiHelper.GenericGetAsync<ProductPhotoshootPagerList>(callUrl);
            dynamic ProductPhotoshootModal = new ExpandoObject();
            ProductPhotoshootModal.Lists = photoshootPagerList.photoshootsInfo;
            ProductPhotoshootModal.PhotoshootID = photoshootId;
            return View("InProgressPhotoshootProductsViewAjax", ProductPhotoshootModal);
        }

        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: List all photoshoot products those are SentToEditor from this api url "/Photoshoots/SentToEditorPhotoshoot/"
        URL: /Photoshoots/sentToEditor/
        Input: Null
        output: dynamic ExpandoObject of Photoshoot SentToEditor Products
        */
        [Authorize]
        public async Task<IActionResult> sentToEditor()
        {
            var products = await _BadgerApiHelper.GetAsync<List<ProductPhotoshootRep>>("/Photoshoots/SentToEditorPhotoshoot/");
            return View("SentToEditor", products);
        }


        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: All photoshoot and models from this api url "/Photoshoots/GetPhotoshootsAndModels/"
        URL: /Photoshoots/getPhotoshootAndModels/
        Input: Null
        output: Json string of photoshoot and models 
        */
        [Authorize]
        [HttpGet("photoshoots/getPhotoshootAndModels/")]
        public async Task<string> getPhotoshootAndModelsAsync()
        {
            Object photoshootPagerList = await _BadgerApiHelper.GenericGetAsync<Object>("/Photoshoots/GetPhotoshootsAndModels/");
            return photoshootPagerList.ToString() ;
        }

        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: List all photoshoots from this api url "/Photoshoots/summary/"
        URL: /Photoshoots/summary/
        Input: Null
        output: dynamic ExpandoObject of Photoshoot Summary
        */
        [Authorize]
        public async Task<IActionResult> summary()
        {
            ProductPhotoshootSummaryPagerList photoshootSummary = await _BadgerApiHelper.GenericGetAsync<ProductPhotoshootSummaryPagerList>("/Photoshoots/summary/");
            dynamic allPhotoshootModels = await _BadgerApiHelper.GenericGetAsync<dynamic>("/PhotoshootModels/list");
            dynamic photoshootSummaryModal = new ExpandoObject();
            photoshootSummaryModal.Lists = photoshootSummary.productPhotoshootSummary;
            photoshootSummaryModal.PhotoshootModels = allPhotoshootModels;
            return View("Summary", photoshootSummaryModal);
        }

        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: Create JObject to add product in photoshoot using this api url "/Photoshoots/StartProductPhotoshoot/{product_id}"
        URL: /Photoshoots/addProductInPhotoshoot/1/100
        Input: ProductID, PhotoshootID
        output: string success or failed
        */
        [Authorize]
        [HttpPost("photoshoots/addProductInPhotoshoot/{photoshoot_id}")]
        public async Task<string> addProductInPhotoshoot(int photoshoot_id, [FromBody] PhotoshootWithItems photoshoot)
        {
            string user_id = await _ILoginHelper.GetLoginUserId();

            var assignPhotoshoot = new ProductPhotoshoots();
            assignPhotoshoot.photoshoot_id = photoshoot_id;
            assignPhotoshoot.product_shoot_status_id = 1;
            assignPhotoshoot.updated_by =int.Parse(user_id);
            assignPhotoshoot.updated_at = _common.GetTimeStemp();
            assignPhotoshoot.products = photoshoot.products;
            assignPhotoshoot.items = photoshoot.items;
            // await _BadgerApiHelper.PostAsync<string>(photoshoot.items, "/photoshoots/bulkupdatebarcode");
            var AssignPhotoshootStatus = await _BadgerApiHelper.PostAsync<string>(assignPhotoshoot, "/photoshoots/StartProductPhotoshoot");
            
            return AssignPhotoshootStatus;
        }

        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: Update product photoshoot status for single product using this api url "/Photoshoots/UpdatePhotoshootProductStatus/{product_id}"
        URL: /Photoshoots/addProductInPhotoshoot/1/NotStarted
        Input: ProductID, Status
        output: string success or failed
        */
        [Authorize]
        [HttpGet("photoshoots/UpdatePhotoshootProductStatus/{product_id}/{status}")]
        public async Task<string> UpdatePhotoshootProductStatus(string product_id, string status)
        { 
            string user_id = await _ILoginHelper.GetLoginUserId();
            
            JObject photoshoot = new JObject();
            photoshoot.Add("product_shoot_status_id", status);
            photoshoot.Add("updated_by", user_id);
            photoshoot.Add("updated_at", _common.GetTimeStemp());

            string returnStatus = await _BadgerApiHelper.GenericPutAsyncString<string>(photoshoot.ToString(Formatting.None), "/Photoshoots/UpdatePhotoshootProductStatus/" + product_id);
            return returnStatus;
        }

        /*
        Developer: Mohi
        Date: 7-3-19 
        Action: Create JObject of photoshoot to add new and add product in that photoshoot using this api url "/Photoshoots/create/{product_id}" and "/photoshoots/StartProductPhotoshoot/{product_id}"
        URL: /Photoshoots/addNewPhotoshoot/1/NotStarted
        Input: FromBody   
        output: string success or failed
        */
        [Authorize]
        [HttpPost("photoshoots/addNewPhotoshoot")]
        public async Task<String> addNewPhotoshoot([FromBody] Photoshoots photoshootDto)
        {
            string user_id = await _ILoginHelper.GetLoginUserId();

            photoshootDto.active_status = 1;
            photoshootDto.created_by = int.Parse(user_id);
            photoshootDto.created_at = _common.GetTimeStemp();
            photoshootDto.updated_at = 0;

badger_view/Views/Photoshoots/InProgressPhotoshootProductsViewAjax.cshtml
@{
    Layout = null;
}
<div class="table-responsive card-body ">
    <table id="openphotoshot" class="table table-bordered datatable_js_ps" style="width:100%">
        <thead>
            <tr>
                <th style="width:50px;" class="no-sort"> </th>
                <th style="width:90px;" class="no-sort">
                    <div class="dropdown">
                        <a class="th-dropdown dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Actions
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item select_menu " href="#" onclick="selectAllCheckbox(this)">Select All</a>
                            <a class="dropdown-item unselect_menu" href="#" onclick="unselectAllCheckbox(this)">Unselect All</a>
                            <a class="dropdown-item" href="#" onclick="updateMultipleProductStatusOnInprogress(@Model.PhotoshootID, '2');">Mark selected as "Send to editor"</a>
                            <a class="dropdown-item" href="#" onclick="updateMultipleProductStatusOnInprogress(@Model.PhotoshootID, '0');">Mark selected as "Shoot not started"</a>
                        </div>
                    </div>
                </th>
                <th>Vendor</th>
                <th>Style Name</th>
                <th>Color</th>
                <th>SKU</th>
                <th>Added by</th>
                <th> Photoshoot Status </th>
            </tr>
        </thead>
        <tbody>
            @foreach (GenericModals.Models.ProductPhotoshootRep photoshoot in Model.Lists)
            {

                <tr style="">
                    <td class="text-center">
                        <input type="checkbox" name="productCheckBox" value="@photoshoot.product_id" class="select-box">
                    </td>
                    <td><img style="width:85px;" src="@photoshoot.product_vendor_image"></td>
                    <td>@photoshoot.vendor_name</td>
                    <td>@photoshoot.product_name</td>
                    <td><b>@photoshoot.color</b></td>
                    <td><b>@photoshoot.sku_family</b></td>
                    <td>@photoshoot.username</td>
                    <td id="shootRow_@photoshoot.product_id">
                        <select class="browser-default custom-select" onchange="updatephotoshootStatus(@photoshoot.product_id,@photoshoot.photoshoot_id, this.value)">
                            <option value="0">Shoot not started</option>
                            <option value="1" selected>Shoot in-progress</option>
                            <option value="2">Send to editor</option>
                        </select>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
 

badger_view/Views/Photoshoots/SentToEditor.cshtml
@{
    ViewData["Title"] = "Sent to editor Photoshoots";
}
@model List<GenericModals.Models.ProductPhotoshootRep>
@section Scripts {
    <script src="~/js/photoshootListing.js" asp-append-version="true"></script>
    }
 
<div class="row">
    <div class="col-md-8 col-sm-12">
        <h4 class="">Sent to editor</h4>
    </div>
</div>

<div class="table-responsive pt-5">
    <table id="openphotoshot" class="table table-bordered datatable_js_ps" style="width:100%">
        <thead>
            <tr>
                <th style="width:50px;"> </th>
                <th style="width:90px;">
                    <div class="dropdown">
                        <a class="th-dropdown dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Actions
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                             <a class="dropdown-item select_menu" href="#" onclick="selectAllCheckbox(this)">Select All</a>
                            <a class="dropdown-item unselect_menu" href="#" onclick="unselectAllCheckbox(this)">Unselect All</a>
                            <a class="dropdown-item" href="#" onclick="updateMultipleProductStatusOnSentToEditor('0')">Mark selected as "Shoot not started"</a>
                        </div>
                    </div>
                </th>
                <th>Vendor</th>
                <th>Style Name</th>
                <th>Color</th>
                <th>SKU</th>
                <th>Item Status</th>
                <th> Photoshoot Status </th>
            </tr>
        </thead>
        <tbody>
           @foreach (var photoshoot in Model)
            {

                <tr style="">
                    <td class="text-center">
                        <input type="checkbox" name="productAddToShootNotStarted" value="@photoshoot.product_id" class="select-box">
                    </td>
                    <td><img style="width:85px;" src="@photoshoot.product_vendor_image"></td>
                    <td>@photoshoot.vendor_name</td>
                    <td>@photoshoot.product_name</td>
                    <td><b>@photoshoot.color</b></td>
                    <td><b>@photoshoot.sku_family</b></td>
                    <td>@photoshoot.po_status</td>
                    <td id="shootRow_@photoshoot.product_id">
                        <select class="browser-default custom-select" onchange="changeShootStatusOnSendToEditor(@photoshoot.product_id, this.value)">
                            <option value="0">Shoot not started</option>
                            <option value="2" selected>Sent to editor</option>
                        </select>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

<div class="loading-box">
    <div class="inner-loading"><div class="spinner-border  text-light" role="status" style=" "><span class="sr-only">Loading...</span></div></div>
</div>

badger_view/Views/Photoshoots/inprogress.cshtml
@{
    ViewData["Title"] = "In-Progress Photoshoots";
}

<div class="row">
    <div class="col-md-3 col-sm-12">
        <h4>In-Progress Photoshoots</h4>
    </div>
    <div class="col-md-9 text-right">
        <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#modaladdmodel">
            Add a Model
        </button>
    </div>
</div>
<div class="table-responsive pt-5">
    <table id="openpo" class="table   table-bordered " style="width:100%;">
        <thead>
            <tr>
                <th>Model</th>
                <th>Scheduled Date</th>
                <th>Stlye (count)</th>
                <th>Notes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <select id="inputState" class="form-control">
                        <option selected>Alexis</option>
                        <option>...</option>
                    </select>
                </td>
                <td><input type="date" class="form-control" /></td>
                <td>1</td>
                <td><input type="text" class="form-control" /></td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm">
                        Edit Photoshoot
                    </button>
                </td>
            </tr>
            <tr>
                <td>
                    <select id="inputState" class="form-control">
                        <option selected>Alexis</option>
                        <option>...</option>
                    </select>
                </td>
                <td><input type="date" class="form-control" /></td>
                <td>1</td>
                <td><input type="text" class="form-control" /></td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm">
                        Edit Photoshoot
                    </button>
                </td>
            </tr>
            <tr>
                <td>
                    <select id="inputState" class="form-control">
                        <option selected>Alexis</option>
                        <option>...</option>
                    </select>
                </td>
                <td><input type="date" class="form-control" /></td>
                <td>1</td>
                <td><input type="text" class="form-control" /></td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm">
                        Edit Photoshoot
                    </button>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>Model</th>
                <th>Scheduled Date</th>
                <th>Stlye (count)</th>
                <th>Notes</th>
                <th></th>
            </tr>
        </tfoot>
    </table>
</div>


<!-- Modal Add Model -->
<div class="modal fade" id="modaladdmodel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="exampleModalLongTitle">Add a new Model</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label>Full Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group col-md-2">
                                <label>Height</label>
                                <select id="inputState" class="form-control">
                                    <option>6</option>
                                    <option>...</option>
                                </select>
                            </div>
                            <div class="form-group col-md-2">
                                <label>Hair</label>
                                <select id="inputState" class="form-control">
                                    <option>B</option>
                                    <option>...</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Ethnicity</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" style="margin: 0 auto;">Submit</button>
            </div>
        </div>
    </div>
</div>

badger_view/Views/Photoshoots/shootInProgress.cshtml
@{
    ViewData["Title"] = "In-Progress Photoshoots";
}
@model dynamic
@section Scripts {
    <script src="~/js/photoshootListing.js" asp-append-version="true"></script>
    <script src="~/js/common.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function () {
            if ($(".PhotoshootList").length == 0) {
                $("#no_result").fadeIn(200);
            }
            var selected = $("#selectedPhotoshootId").val();
            if (selected != "0") {
                $("#heading_" + selected + " .btn-link").click();
            } else {
                $(".card-header .btn-link:first").click();
            }


        })
    </script>
}

<div class="">
    <div class="accordion" id="accordionShootInProgress">
        <h1>
            @{
                dynamic selectedPhotoshoot = Model.SelectedPhotoshoot;
            }  <input type="hidden" id="selectedPhotoshootId" value="@selectedPhotoshoot" />
        </h1>
        @foreach (GenericModals.Models.ProductPhotoshootInProgressRep inProgress in Model.Lists)
        {
        <div class="card PhotoshootList" id="inprogressContainer_@inProgress.photoshoot_id">
            <div class="card-header" id="heading_@inProgress.photoshoot_id" data-photoshootId="@inProgress.photoshoot_id">
                <h2 class="mb-0">
                    <button type="button" class="btn btn-link collapsButton" data-toggle="collapse" data-target="#collapse_@inProgress.photoshoot_id">
                        <i class="fa fa-plus"></i>
                        <span class="text-dark font-weight-bold h5">@inProgress.photoshoot_name</span>
                    </button>
                </h2>
            </div>
            <div class="loading-box-light"><div class="spinner-border" role="status" style=" "><span class="sr-only">Loading...</span></div></div>
            <div id="collapse_@inProgress.photoshoot_id" class="collapse" aria-labelledby="heading_@inProgress.photoshoot_id" data-parent="#accordionShootInProgress">

            </div>
        </div>
        }

    </div>
</div>

<div class="row" id="no_result" style="display:none;">
    <div class="col-md-12 col-sm-12">
        <h4 class="">Photo In-Progress </h4>
    </div>

    <div class="col-md-12 col-sm-12">
        <p>No data available</p>
    </div>
</div>

@section page_popup_area{
    <div class="loading-box">
        <div class="inner-loading"><div class="spinner-border  text-light" role="status" style=" "><span class="sr-only">Loading...</span></div></div>
    </div>
}

badger_view/Views/Photoshoots/summary.cshtml
@{
    ViewData["Title"] = "In-Progress Photoshoot";
}
@model dynamic
@section Scripts {
    <script src="~/js/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/jquery-ui.css" />
    <!-- <script src="~/lib/date-picker/js/gijgo.min.js" type="text/javascript"></script>
    <link href="~/lib/date-picker/css/gijgo.min.css" rel="stylesheet" type="text/css" /> -->
    <script src="~/js/photoshootListing.js" asp-append-version="true"></script>
    <script>
        $('.photoshootDate').each(function (index, value) {
            var id = $(this).attr('id');
            $('#' + id).datepicker({
                onClose: function (date, datepicker) {
                    if (date != "") {
                        editPhotoshootSummary(id.replace("date_",""));
                    }
                },
                dateFormat: 'm/d/yy',

            });
        });
    </script>
}
@using CommonHelper;    
<div class="row">
    <div class="col-md-8 col-sm-12">
        <h4 class="">In-Progress Photoshoot</h4>
    </div>
    <div class="col-md-4 col-sm-12 " id="AddModelBtnDiv">
        <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#modaladdmodel">
            Add a Model
        </button>
    </div>
</div>

<div class="table-responsive pt-5">
    <table id="openphotoshot" class="table table-bordered datatable_js_ps" style="width:100%">
        <thead>
            <tr>
                <th class="text-center">Model</th>
                <th class="text-center">Scheduled Date</th>
                <th class="text-center">Styles (count)</th>
                <th class="text-center">Notes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (GenericModals.Models.ProductPhotoshootSummaryRep photoshoot in Model.Lists)
            {
                <tr id="rowId_@photoshoot.photoshoot_id">
                    <td class="text-center">
                        <select class="browser-default custom-select" onchange="editPhotoshootSummary(@photoshoot.photoshoot_id);">
                            <option value="">Choose...</option>
                            @foreach (dynamic ShootModel in Model.PhotoshootModels)
                            {
                                @if (@ShootModel.model_id == @photoshoot.model_id)
                                {
                                    <option value="@ShootModel.model_id" selected="selected">@ShootModel.model_name </option>
                                }
                                else
                                {
                                    <option value="@ShootModel.model_id">@ShootModel.model_name </option>
                                }
                            }
                        </select>
                    </td>

                    <td class="text-center">
                        @{ var scheduled_date = new CommonHelper().ConvertToDate(@photoshoot.scheduled_date); }
                        <input type="text" value="@scheduled_date" class="photoshootDate browser-default scheduled_date form-control" id="date_@photoshoot.photoshoot_id" >
                    </td>
                    <td class="text-center"><b>@photoshoot.styles</b></td>
                    <td class="text-center ps_notes" id="notesRow_@photoshoot.photoshoot_id">
                        <textarea class="form-control notes" rows="2" cols="25" data-id="@photoshoot.photoshoot_id" onblur="AddPhotoshootSummaryNotes(@photoshoot.photoshoot_id);"></textarea>
                    </td>
                    <td class="text-center">
                        <a class=""  asp-controller="Photoshoots" asp-action="shootInProgress/@photoshoot.photoshoot_id">
                                <input type="button" class="btn btn-default btn-green" value="Edit Photoshoot">
                        </a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

@section page_popup_area{

    <div class="loading-box">
        <div class="inner-loading"><div class="spinner-border  text-light" role="status" style=" "><span class="sr-only">Loading...</span></div></div>
    </div>

    <!-- Modal Add Model -->
    <div class="modal fade" id="modaladdmodel" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="">Add a new Model</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <form id="NewModelForm">
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label>Full Name</label>
                                    <input type="text" class="form-control" id="model_name">
                                </div>
                                <div class="form-group col-md-2">
                                    <label>Height</label>
                                    <input type="text" class="form-control" id="model_height">
                                </div>
                                <div class="form-group col-md-2">
                                    <label>Hair</label>
                                    <input type="text" class="form-control" id="model_hair">
                                </div>
                                <div class="form-group col-md-4">
                                    <label>Ethnicity</label>
                                    <input type="text" class="form-control" id="model_ethnicity">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="addNewPhotoshootModel('summary');" style="margin: 0 auto;">Submit</button>
                </div>
            </div>
        </div>
    </div>
}