badger_view/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GenericModals.Models;
using badger_view.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace badger_view.Controllers
{
    public class HomeController : Controller
    {
        ILoginHelper _LoginHelper;
        public HomeController(ILoginHelper loginHelper)
        {
            _LoginHelper = loginHelper;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View();
        }
        [HttpPost("Dologin")]
        public async Task<IActionResult> DoLogin()
        {
            return View("Login");

        }
        [Authorize]
        public async Task<IActionResult> About()
        {
            ViewData["Message"] = "Your application description page.";
            
            return View();
        }
        [Authorize]
        public async Task<IActionResult> Contact()
        {
            ViewData["Message"] = "Your contact page.";
            return View();
        }
        [Authorize]
        public async Task<IActionResult> Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Form()
        {
            return View();
        }
    }
}

badger_view/Controllers/PurchaseOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using badger_view.Helpers;
using GenericModals.Models;
using System.Dynamic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CommonHelper;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using GenericModals.Claim;
using GenericModals.PurchaseOrder;
using GenericModals;
using CommonHelper.Extensions;

namespace badger_view.Controllers
{
    public class purchaseOrderFileData
    {
        public List<IFormFile> purchaseOrderDocuments { get; set; }
        public string po_id { get; set; }
        public string doc_type { get; set; }
    }
    public class PurchaseOrdersController : Controller
    {
        private readonly IConfiguration _config;

        private CommonHelper.CommonHelper _common = new CommonHelper.CommonHelper();
        private CommonHelper.awsS3helper awsS3Helper = new CommonHelper.awsS3helper();
        private String UploadPath = "";
        private String S3bucket = "";
        private String S3folder = "";

        private ILoginHelper _LoginHelper;

        ILoggerFactory _loggerFactory;

        /********** Document Types **************************/
        private int original_po = 4;
        private int shipment_invoice = 7;
        private int main_shipment_invoice = 8;
        private int other = 9;

        private int default_pagination = 50;

        public PurchaseOrdersController(IConfiguration config, ILoginHelper LoginHelper, ILoggerFactory loggerFactory, BadgerApiHelper badgerApiHelper)
        {
            _LoginHelper = LoginHelper;
            _config = config;
            UploadPath = _config.GetValue<string>("UploadPath:path");
            S3bucket = _config.GetValue<string>("S3config:Bucket_Name");
            S3folder = _config.GetValue<string>("S3config:Folder");
            _loggerFactory = loggerFactory;
            _BadgerApiHelper = badgerApiHelper;
        }
        private BadgerApiHelper _BadgerApiHelper;

        /*
        Developer: Sajid Khan
        Date: 7-5-19 
        Action: View ALL Purchase Orders List & Get All Vendors with id and name & Get All Vendor types using badger api helper and common helper   
        URL: /purchaseorders
        Request: Get
        Input: Null
        output: Dynamic object of purchase orders
        */
        [Authorize]
        public async Task<IActionResult> Index()
        {
            

            // PurchaseOrdersPagerList purchaseOrdersPagerList = await _BadgerApiHelper.GenericGetAsync<PurchaseOrdersPagerList>("/purchaseorders/listpageview/0/0/true");
            var purchaseOrdersPagerList = await _BadgerApiHelper.GetAsync<PurchaseOrdersPagerList>("/purchaseorders/listpageview/0/0/true"); 

            String poIdsList = "";

            dynamic ProductIdsList = await _BadgerApiHelper.GenericGetAsync<object>("/product/getproductidsbypurchaseorder/");

            List<VendorType> getVendorTypes = await _BadgerApiHelper.GenericGetAsync<List<VendorType>>("/vendor/getvendortypes");

            string DeliveryStartEnd = "";

            string NewDateFormat = "";
            string NumDays = "";

            var TotalList = purchaseOrdersPagerList.purchaseOrdersInfo;

            List<PurchaseOrdersInfo> newPurchaseOrderInfoList = new List<PurchaseOrdersInfo>();
            List<PurchaseOrdersInfo> newPurchaseOrderInfoList2 = new List<PurchaseOrdersInfo>();

            int PhotosCount = 0;
            int TotalPublishedProducts = 0;
            foreach (PurchaseOrdersInfo poList in TotalList)
            {
                PhotosCount = 0;
                TotalPublishedProducts = 0;

                foreach (dynamic ids in ProductIdsList)
                {
                    if (ids.po_id == poList.po_id)
                    {
                        PhotosCount++;
                        poIdsList += ids.product_id + ",";
                    }
                }

                if (PhotosCount != 0)
                {
                    dynamic TotalData = await _BadgerApiHelper.GenericGetAsync<object>("/product/getpublishedproductCount/" + poIdsList.TrimEnd(','));
                    TotalPublishedProducts = TotalData.Count;
                }

                DeliveryStartEnd = _common.MultiDatePickerFormat(poList.delivery_window_start, poList.delivery_window_end);

                double DateToCheck = _common.GetTimeStemp();

                bool CheckDaysRange = false;

                if (DateToCheck <= poList.delivery_window_end || poList.delivery_window_end == 0)
                {
                    CheckDaysRange = true;
                }

                NewDateFormat = _common.ConvertToDate(poList.order_date);
                NumDays = _common.NumberOfDays(poList.updated_at);


                if (CheckDaysRange == true && poList.po_status == 5)
                {
                    newPurchaseOrderInfoList2.Add(new PurchaseOrdersInfo
                    {
                        po_id = poList.po_id,
                        vendor_po_number = poList.vendor_po_number,
                        vendor_invoice_number = poList.vendor_invoice_number,
                        vendor_order_number = poList.vendor_order_number,
                        vendor_id = poList.vendor_id,
                        total_styles = poList.total_styles,
                        shipping = poList.shipping,
                        order_date = poList.order_date,
                        vendor = poList.vendor,
                        custom_delivery_window_start_end = DeliveryStartEnd,
                        po_status = poList.po_status,
                        ra_flag = poList.ra_flag,
                        updated_at = poList.updated_at,
                        custom_order_date = NewDateFormat,
                        num_of_days = NumDays,
                        check_days_range = CheckDaysRange,
                        has_note = poList.has_note,
                        has_doc = poList.has_doc,
                        photos = TotalPublishedProducts,
                        remaining = (PhotosCount - TotalPublishedProducts),
                        Claim = poList.Claim
                    });
                }
                else
                {
                    newPurchaseOrderInfoList.Add(new PurchaseOrdersInfo
                    {
                        po_id = poList.po_id,
                        vendor_po_number = poList.vendor_po_number,
                        vendor_invoice_number = poList.vendor_invoice_number,
                        vendor_order_number = poList.vendor_order_number,
                        vendor_id = poList.vendor_id,
                        total_styles = poList.total_styles,
                        shipping = poList.shipping,
                        order_date = poList.order_date,
                        vendor = poList.vendor,
                        custom_delivery_window_start_end = DeliveryStartEnd,
                        po_status = poList.po_status,
                        ra_flag = poList.ra_flag,
                        updated_at = poList.updated_at,
                        custom_order_date = NewDateFormat,
                        num_of_days = NumDays,
                        check_days_range = CheckDaysRange,
                        has_note = poList.has_note,
                        has_doc = poList.has_doc,
                        photos = TotalPublishedProducts,
                        remaining = (PhotosCount - TotalPublishedProducts),
                        Claim = poList.Claim
                    });
                }
                NewDateFormat = "";
                NumDays = "";
            }

            dynamic PurchaseOrdersPageModal = new ExpandoObject();

            var list = newPurchaseOrderInfoList.Concat(newPurchaseOrderInfoList2).ToList();

            PurchaseOrdersPageModal.PurchaseOrdersCount = purchaseOrdersPagerList.Count;
            PurchaseOrdersPageModal.PurchaseOrdersLists = list;
            PurchaseOrdersPageModal.VendorType = getVendorTypes;

            return View("Index", PurchaseOrdersPageModal);
        }

        /*
        Developer: Sajid Khan
        Date: 7-5-19 
        Action: View Purchase Orders List & Get Note,Document,Tracking,Ledger and Discount by using badger api helper   
        URL: /purchaseorders/listpagination/start/end/boolean
        Request: Get
        Input: int start, int limit, boolean
        output: Dynamic object of purchase orders
        */
        [Authorize]
        [HttpGet("purchaseorders/listpagination/{start}/{limit}/{count}")]
        public async Task<string> ListPagination(int start, int limit, Boolean count)
        {
            

            PurchaseOrdersPagerList purchaseOrdersPagerList = await _BadgerApiHelper.GenericGetAsync<PurchaseOrdersPagerList>("/purchaseorders/listpageview/" + start + "/" + limit + "/" + count);

            string DeliveryStartEnd = "";

            string NewDateFormat = "";
            string NumDays = "";

            var TotalList = purchaseOrdersPagerList.purchaseOrdersInfo;

            List<PurchaseOrdersInfo> newPurchaseOrderInfoList = new List<PurchaseOrdersInfo>();

            foreach (PurchaseOrdersInfo poList in TotalList)
            {
                DeliveryStartEnd = _common.MultiDatePickerFormat(poList.delivery_window_start, poList.delivery_window_end);

                NewDateFormat = _common.ConvertToDate(poList.order_date);
                NumDays = _common.NumberOfDays(poList.updated_at);

                newPurchaseOrderInfoList.Add(new PurchaseOrdersInfo
                {
                    po_id = poList.po_id,
                    vendor_po_number = poList.vendor_po_number,
                    vendor_invoice_number = poList.vendor_invoice_number,

badger_view/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

badger_view/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

badger_view/Views/Home/Form.cshtml
@{
    ViewData["Title"] = "Form";
}

<h1>Form Validation</h1>

<form>
    <div>
        <label for="name">Name:</label>
        <input type="text" name="name" class="name" placeholder="Ola Nordmann" pattern="^[( )a-zA-Z]+$" required />
    </div>
    <div>
        <label for="password">Password:</label>
        <input type="password" name="password" class="password" placeholder="&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;" pattern="(?=^.{8,}$)((?=.*d)|(?=.*W+))(?![.n])(?=.*[A-Z])
(?=.*[a-z]).*" required />
    </div>
    <div>
        <label for="mail">Mail:</label>
        <input type="email" name="mail" class="mail" placeholder="ola@nordmann.no" pattern="^([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})$" required />
    </div>
    <div>
        <label for="phone">Number:</label>
        <input type="tel" name="phone" placeholder="+4700000000" pattern="^\+?(?:[0-9]??).{5,14}[0-9]$" required />
    </div>
    <div>
        <label for="website">Website:</label>
        <input type="url" name="website" placeholder="https://google.com" pattern="(http|https)://.+" required />
    </div>
    <div>
        <label for="date">Date:</label>
        <input type="date" name="date" min="2013-01-01" max="2013-12-31" required />
    </div>
    <div>
        <label for="onechar">Min one char:</label>
        <input type="text" name="onechar" placeholder="x" pattern="[ÆØÅæøåa-zA-Z]+" required />
    </div>
    <div>
        <label for="onechar">Four digit num:</label>
        <input type="text" name="onechar" placeholder="0000" pattern="^[0-9]{4}" required />
    </div>
    <div>
        <input type="submit" />
    </div>
</form>

badger_view/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>Home</h2>


<a href="#" data-toggle="modal" data-target="#modaladdstylec">Add style Item to P.O. &lt;number&gt; - Clothing</a>
<br />
<a href="#" data-toggle="modal" data-target="#modaladdstylea">Add style Item to P.O. &lt;number&gt; - Accessories</a>
<br />
<a asp-area="" asp-controller="PurchaseOrders" asp-action="PurchaseOrdersManagement">P.O. Management Page</a>
<br />
<a asp-area="" asp-controller="Product" asp-action="EditAttributes">Edit Attribute Page</a>
<br />
<a asp-area="" asp-controller="PurchaseOrders" asp-action="Single">Single P.O. Page</a>
<br />
<a asp-area="" asp-controller="PurchaseOrders" asp-action="InventoryReporting">Purchase Orders Inventory - Reporting Page</a>
<br />
<a asp-area="" asp-controller="Home" asp-action="Form">Form Validation</a>
<br />
<a asp-area="" asp-controller="PurchaseOrders" asp-action="PurchaseOrdersCheckIn">PO Check In</a>